- id: front_door_unlocked
  alias: Front Door Unlocked
  trigger:
  - entity_id: lock.schlage_allegion_be469_touchscreen_deadbolt_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: template
    value_template: '{{ not is_state(''person.darren'', ''home'') }}'
  - condition: template
    value_template: '{{ not is_state(''person.lindsay'', ''home'') }}'
  action:
  - data:
      message: '{{ now().strftime(''%Y-%m-%d %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469_touchscreen_deadbolt_locked","friendly_name")
        }} was {{ states("lock.schlage_allegion_be469_touchscreen_deadbolt_locked")
        }} ({{ state_attr("lock.schlage_allegion_be469_touchscreen_deadbolt_locked","lock_status")
        }})'
    service: notify.ios_darreniphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%d %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469_touchscreen_deadbolt_locked","friendly_name")
        }} was {{ states("lock.schlage_allegion_be469_touchscreen_deadbolt_locked")
        }} ({{ state_attr("lock.schlage_allegion_be469_touchscreen_deadbolt_locked","lock_status")
        }})'
    service: notify.ios_lindsays_iphone
- id: side_door_unlocked
  alias: Side Door Unlocked
  trigger:
  - entity_id: lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: template
    value_template: '{{ not is_state(''person.darren'', ''home'') }}'
  - condition: template
    value_template: '{{ not is_state(''person.lindsay'', ''home'') }}'
  action:
  - data:
      message: '{{ now().strftime(''%Y-%m-%d %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked","friendly_name")
        }} was {{ states("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked")
        }} ({{ state_attr("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked","lock_status")
        }})'
    service: notify.ios_darreniphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%d %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked","friendly_name")
        }} was {{ states("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked")
        }} ({{ state_attr("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked","lock_status")
        }})'
    service: notify.ios_lindsays_iphone
- id: HACS_Notification
  alias: HACS Persistent Notification
  trigger:
  - above: '0'
    entity_id: sensor.hacs
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ not is_state(''sensor.hacs'', ''unknown'') }}'
  action:
  - data:
      message: Update available!
      title: HACS
    service: persistent_notification.create
- id: '1566928395360'
  alias: dash_test
  trigger:
  - event_data: {}
    event_type: dash_test
    platform: event
  condition: []
  action:
  - data:
      message: '{{ now().strftime(''%Y-%m-%d %I:%M %p'') }}: dash_test called'
    service: notify.pushbullet_dg
- id: '1566930049220'
  alias: toggle_front_door_lock
  trigger:
  - event_data: {}
    event_type: toggle_front_door_lock
    platform: event
  condition: []
  action:
    service_template: "{% if is_state('lock.schlage_allegion_be469_touchscreen_deadbolt_locked',\
      \ 'locked') %}\n  lock.unlock\n{% else %}\n  lock.lock\n{% endif %}\n"
    entity_id: lock.schlage_allegion_be469_touchscreen_deadbolt_locked
- id: update_darren_travel_work_sensor
  alias: Commute - Update Darren's morning commute sensor
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: time
    after: 06:00:00
    before: 09:00:00
  - condition: time
    weekday:
    - mon
    - wed
    - thu
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.darren_work
- id: update_darren_travel_home_sensor
  alias: Commute - Update Darren's afternoon commute sensor
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: time
    after: '16:30:00'
    before: '20:00:00'
  - condition: time
    weekday:
    - mon
    - wed
    - thu
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.darren_home
- id: start_plex
  alias: start_plex
  trigger:
  - event_data: {}
    event_type: start_plex
    platform: event
  condition: []
  action:
  - service: remote.turn_on
    entity_id: remote.living_room
    data:
      entity_id: remote.living_room
      activity: Watch Fire TV
  - service: media_player.select_source
    entity_id: media_player.fire_tv
    data:
      source: com.plexapp.android
- id: alert_front_door_deadbolt_battery_low
  alias: 'ALERT: Front Door Deadbolt Battery Low'
  trigger:
  - platform: template
    value_template: '{{ state_attr("zwave.schlage_allegion_be469_touchscreen_deadbolt","battery_level") != None
      and state_attr("zwave.schlage_allegion_be469_touchscreen_deadbolt","battery_level") | int < 30 }}'
  action:
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469_touchscreen_deadbolt_locked","friendly_name")
        }} has low battery! ({{ state_attr("zwave.schlage_allegion_be469_touchscreen_deadbolt","battery_level")
        }}%)'
    service: notify.ios_darreniphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469_touchscreen_deadbolt_locked","friendly_name")
        }} has low battery! ({{ state_attr("zwave.schlage_allegion_be469_touchscreen_deadbolt","battery_level")
        }}%)'
    service: notify.ios_lindsays_iphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469_touchscreen_deadbolt_locked","friendly_name")
        }} has low battery! ({{ state_attr("zwave.schlage_allegion_be469_touchscreen_deadbolt","battery_level")
        }}%)'
    service: notify.pushbullet_dg
- id: alert_side_door_deadbolt_battery_low
  alias: 'ALERT: Side Door Deadbolt Battery Low'
  trigger:
  - platform: template
    value_template: '{{ state_attr("zwave.schlage_allegion_be469zp_connect_smart_deadbolt","battery_level") != None
      and state_attr("zwave.schlage_allegion_be469zp_connect_smart_deadbolt","battery_level") | int < 30 }}'
  action:
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked","friendly_name")
        }} has low battery! ({{ state_attr("zwave.schlage_allegion_be469zp_connect_smart_deadbolt","battery_level")
        }}%)'
    service: notify.ios_darreniphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked","friendly_name")
        }} has low battery! ({{ state_attr("zwave.schlage_allegion_be469zp_connect_smart_deadbolt","battery_level")
        }}%)'
    service: notify.ios_lindsays_iphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %I:%M %p'') }}: {{ state_attr("lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked","friendly_name")
        }} has low battery! ({{ state_attr("zwave.schlage_allegion_be469zp_connect_smart_deadbolt","battery_level")
        }}%)'
    service: notify.pushbullet_dg
- id: harmony_plex
  alias: Harmony Plex
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Home
  action:
  - service: media_player.select_source
    entity_id: media_player.fire_tv
    data:
      source: com.plexapp.android
- id: update_ams_day
  alias: Update AMS Day
  trigger:
  - at: 00:01:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.zach_school
    state: 'on'
  action:
  - data:
      entity_id: input_number.ams_counter
    service: input_number.increment
- id: ifttt_unlock_side_door
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
- alias: 'Start HomeKit'
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
  action:
    - service: homekit.start
- id: toggle_kitchen_sink_light
  alias: toggle_kitchen_sink_light
  trigger:
  - event_data: {}
    event_type: toggle_kitchen_sink_light
    platform: event
  condition: []
  action:
    service_template: "{% if is_state('light.55002573dc4f225b92d5',\
      \ 'off') %}\n  light.turn_on\n{% else %}\n  light.turn_off\n{% endif %}\n"
    data:
      entity_id: light.55002573dc4f225b92d5
#      rgb_color: [255,255,255]
#      brightness: 255
#      color_temp: 1000
