- id: '1566616270957'
  alias: Side Door Unlocked
  trigger:
  - entity_id: lock.schlage_allegion_be469_touchscreen_deadbolt_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: template
    value_template: '{{ not is_state(''person.darren'', ''home'') }}'
  - condition: template
    value_template: '{{ not is_state(''person.lindsay'', ''home'') }}'
  action:
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %l:%M %p'') }}: {{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.attributes.friendly_name
        }} was {{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.state
        }} ({{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.attributes.lock_status
        }})'
    service: notify.ios_darreniphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %l:%M %p'') }}: {{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.attributes.friendly_name
        }} was {{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.state
        }} ({{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.attributes.lock_status
        }})'
    service: notify.ios_lindsays_iphone
- id: HACS_Notification
  alias: HACS Persistent Notification
  trigger:
  - above: '0'
    entity_id: sensor.hacs
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ not is_state(''sensor.hacs'', ''unknown'') }}'
  action:
  - data:
      message: Update available!
      title: HACS
    service: persistent_notification.create
- id: '1566928395360'
  alias: dash_test
  trigger:
  - event_data: {}
    event_type: dash_test
    platform: event
  condition: []
  action:
  - data:
      message: '{{ now().strftime(''%Y-%m-%d %l:%M %p'') }}: dash_test called'
    service: notify.pushbullet_dg
- id: '1566930049220'
  alias: toggle_side_door_lock
  trigger:
  - event_data: {}
    event_type: toggle_side_door_lock
    platform: event
  condition: []
  action:
    service_template: "{% if is_state('lock.schlage_allegion_be469_touchscreen_deadbolt_locked',\
      \ 'locked') %}\n  lock.unlock\n{% else %}\n  lock.lock\n{% endif %}\n"
    entity_id: lock.schlage_allegion_be469_touchscreen_deadbolt_locked
- id: update_darren_morning_commute_sensor
  alias: "Commute - Update Darren's morning commute sensor"
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: '/2'
  condition:
    - condition: time
      after: '06:30:00'
      before: '09:00:00'
    - condition: time
      weekday:
        - mon
#        - tue
        - wed
        - thu
#        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.darren_morning_commute
- id: update_darren_afternoon_commute_sensor
  alias: "Commute - Update Darren's afternoon commute sensor"
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: '/2'
  condition:
    - condition: time
      after: '16:30:00'
      before: '20:00:00'
    - condition: time
      weekday:
        - mon
#        - tue
        - wed
        - thu
#        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.darren_afternoon_commute
- id: start_plex
  alias: start_plex
  trigger:
  - event_data: {}
    event_type: start_plex
    platform: event
  condition: []
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        entity_id: remote.living_room
        activity: 'Watch Fire TV'
    - service: media_player.select_source
      entity_id: media_player.fire_tv
      data:
        source: com.plexapp.android
- id: alert_side_door_deadbolt_battery_low
  alias: 'ALERT: Side Door Deadbolt Battery Low'
  trigger:
  - platform: template
    value_template: '{{ states.zwave.schlage_allegion_be469_touchscreen_deadbolt.attributes.battery_level | int < 30 }}'
  action:
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %l:%M %p'') }}: {{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.attributes.friendly_name }} has low battery! ({{ states.zwave.schlage_allegion_be469_touchscreen_deadbolt.attributes.battery_level }}%)'
    service: notify.ios_darreniphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %l:%M %p'') }}: {{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.attributes.friendly_name }} has low battery! ({{ states.zwave.schlage_allegion_be469_touchscreen_deadbolt.attributes.battery_level }}%)'
    service: notify.ios_lindsayiphone
  - data:
      message: '{{ now().strftime(''%Y-%m-%y %l:%M %p'') }}: {{ states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked.attributes.friendly_name }} has low battery! ({{ states.zwave.schlage_allegion_be469_touchscreen_deadbolt.attributes.battery_level }}%)'
    service: notify.pushbullet_dg
