- platform: workday
  name: darren_work
  country: US
  province: MA
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]

- platform: workday
  name: zach_school
  country: US
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays:
    - '2019-11-05'
    - '2019-11-29'
    - '2019-12-23'
    - '2019-12-24'
    - '2019-12-26'
    - '2019-12-27'
    - '2019-12-28'
    - '2019-12-29'
    - '2019-12-30'
    - '2019-12-31'
    - '2020-01-02'
    - '2020-02-18'
    - '2020-02-19'
    - '2020-02-20'
    - '2020-02-21'
    - '2020-03-13'
    - '2020-04-10'
    - '2020-04-20'
    - '2020-04-21'
    - '2020-04-22'
    - '2020-04-23'
    - '2020-04-24'

- platform: tod
  name: morning
  after: '22:00'
#  after_offset: '-02:00'
  before: '11:00'

- platform: template
  sensors:
    trash_pickup_soon:
      value_template: >-
        {{ state_attr("sensor.trash","days") < 3
           and not (state_attr("sensor.trash","days") == 0
               and states("binary_sensor.morning") == "off") }}
    recycling_pickup_soon:
      value_template: >-
        {{ state_attr("sensor.recycling","days") < 3
           and not (state_attr("sensor.recycling","days") == 0
               and states("binary_sensor.morning") == "off") }}
