
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3 ### optional

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include themes.yaml
  javascript_version: es5

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switch.yaml
zone: !include zone.yaml
binary_sensor: !include binary_sensor.yaml

homeassistant:
  customize: !include customize.yaml
  time_zone: America/New_York
  whitelist_external_dirs:
    - '/config/www/'

input_number:
  ams_counter:
#    name: Slider
#    initial: 2
    min: 0
    max: 360
    step: 1

notify:
  - name: pushbullet_dg
    platform: pushbullet
    api_key: !secret pushbullet_key

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.42.100

sensor: !include sensor.yaml

media_player:
  - platform: plex
  - platform: androidtv
    name: Fire TV
    host: 192.168.42.119
    adbkey: "/config/android/adbkey"
    device_class: firetv

python_script:

hacs:
  token: !secret hacs_token
  theme: true
  python_script: true
  appdaemon: true

discovery:
  ignore:
    - igd

ios:

logger:
  default: warning
  logs:
#    homeassistant.components.google_travel_time: debug
#    hacs: debug
#    homeassistant.components.life360.device_tracker: debug
    homeassistant.components.generic: debug

lovelace:
  mode: yaml

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060
      advertise_ip: 192.168.42.26
      advertise_port: 8060
#      host_ip: 192.168.42.26

homekit:
  auto_start: false
  filter:
    exclude_domains:
      - automation
      - input_boolean
#      - script
    exclude_entities:
      - sensor.darren_home
      - sensor.darren_work
      - sensor.lindsay_home
      - sensor.lindsay_work
      - sensor.lindsay_gymnastics

tuya:
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: "1"

camera:
  - platform: generic
    name: plex_image
    still_image_url: >
      {% if states('media_player.plex_fire_tv') == 'playing' %}
        {{ state_attr('media_player.plex_fire_tv', 'entity_picture') }}
      {% else %}
        /local/images/plex_black.png
      {% endif %}
