resources:
  - url: /community_plugin/content-card-remote-control/content-card-remote-control.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /community_plugin/entity-attributes-card/entity-attributes-card.js
    type: js
  - url: /community_plugin/card-tools/card-tools.js
    type: js
  - url: /community_plugin/lovelace-card-templater/lovelace-card-templater.js
    type: js
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module
  - url: /community_plugin/garbage-collection-card/garbage-collection-card.js
    type: module
title: Unicorn Circle
views:
  - badges:
      - person.darren
      - person.lindsay
      - sensor.ams_day
      - sensor.harmony_activity
      - sensor.plex_now_playing
      - sensor.plex
      - sensor.hacs
      - sun.sun
    cards:
      - type: vertical-stack
        cards:
          - type: custom:garbage-collection-card
            entity: sensor.trash
            icon_size: 35px
            icon_color: green
            hide_date: true
          - type: custom:garbage-collection-card
            entity: sensor.recycling
            icon_color: '#0561ba'
            hide_date: true
          - entity: weather.dark_sky
            type: custom:weather-card
            icons: "/community_plugin/weather-card/icons/"
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.morning
                state: 'on'
            card:
              type: entities
              entities:
                - sensor.darren_work
#              - sensor.darren_home
                - sensor.lindsay_work
#              - sensor.lindsay_gymnastics
#              - sensor.lindsay_home
 #           title: Travel
              show_header_toggle: false
          - type: conditional
            conditions:
              - entity: binary_sensor.morning
                state: 'off'
            card:
              type: entities
              entities:
#                - sensor.darren_work
              - sensor.darren_home
#                - sensor.lindsay_work
              - sensor.lindsay_gymnastics
              - sensor.lindsay_home
 #           title: Travel
              show_header_toggle: false
          - type: entities
            entities:
              - lock.schlage_allegion_be469_touchscreen_deadbolt_locked
#              - automation.front_door_unlocked
              - lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked
#              - automation.side_door_unlocked
  #          title: Doors
            show_header_toggle: false
      - type: map
        aspect_ratio: 16:9
        default_zoom: 30
        entities:
          - person.darren
          - person.lindsay
          - zone.home
    path: default_view
    title: Home
  - badges: []
    cards:
      - type: vertical-stack
        cards:
          - entities:
            - switch.firetv
            - switch.xbox_one
            - switch.switch
            - switch.tv
            - switch.smarttv
            title: Switch
            type: entities
          - type: "custom:button-entity-row"
            buttons:
              - entity: script.start_plex
                icon: "mdi:plex"
                name: Start Plex
                style:
                  - color: var(--primary-color)
          - entity: media_player.fire_tv
            type: media-control
      - entity: sensor.plex_recently_added
        type: custom:upcoming-media-card
        image_style: fanart
        hide_unflagged: true
        title: New On Plex...
    icon: 'mdi:remote'
    path: harmony-remote
    title: Harmony Remote
  - cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            title: Harmony
            entities:
              - switch.xbox_one
              - switch.tv
              - switch.smarttv
              - switch.switch
              - switch.firetv
            state_image:
              "PowerOff": /local/images/power_off.png
              "Xbox One": /local/images/xbox_one_logo.png
              "Fire TV": /local/images/wiiu_logo.png
              "Smart TV": /local/images/windows_logo.png
              "Switch": /local/images/nintendo_switch_logo.png
              "TV": /local/images/sony_logo.png
            entity: sensor.harmony_activity
          - type: entity-filter
            entities:
              - sensor.xbox_live_name
              - sensor.xbox_current
            state_filter:
              - 'Online'
              - 'Home'
              - 'Netflix'
            show_empty: false
      - type: vertical-stack
        cards: 
          - type: picture-glance
            title: Yamaha Receiver
            entities:
              - switch.zone_1
              - switch.audio_1
              - switch.zone_2
              - switch.audio_2
            image: /local/images/sony_receiver.jpg
          - type: conditional
            conditions:
              - entity: switch.zone_1
                state: 'on'
              - entity: switch.zone_2
                state: 'on'
            card:
              type: entities
              entities:
                - entity: input_number.yamaha_receiver
                  name: Zone 1 Volume
                - entity: input_number.yamaha_receiver_zone_2
                  name: Zone 2 Volume
          - type: conditional
            conditions:
              - entity: switch.zone_1
                state: 'on'
              - entity: switch.zone_2
                state: 'off'
            card:
              type: entities
              entities:
                - entity: input_number.yamaha_receiver
                  name: Volume
          - type: conditional
            conditions:
              - entity: switch.zone_1
                state: 'off'
              - entity: switch.zone_2
                state: 'on'
            card:
              type: entities
              entities:
                - entity: input_number.yamaha_receiver_zone_2
                  name: Volume
    title: Harmony Remote 2
  - title: playground
    cards:
      - type: custom:garbage-collection-card
        entity: sensor.trash
        icon_size: 35px
        icon_color: green
        hide_date: true
      - type: custom:garbage-collection-card
        entity: sensor.recycling
        icon_color: '#0561ba'



#      - type: 'custom:card-templater'
#        card:
#          type: horizontal-stack
#          cards:
#            - entity: sensor.trash_pickup
#              name: Trash
#              type: sensor
#            - entity: sensor.recycling_pickup
#              name: Recycling
#              type: sensor
